server:
  port: 8080
api:
  prefix: api/v1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commerce?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 240123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
jwt:
    expiration: 259200 #3 days = 3 * 24 * 60 * 60
    secretKey: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
logging:
    level:
        org:
            springframework:
            security: DEBUG
    file:
      name: logs/dev.log